server:
  port: ${PROMOTION_SERVICE_PORT:8098}
  servlet:
    context-path: /promotion

spring:
  application:
    name: promotion-service
  data:
    mongodb:
      uri: mongodb://${MONGO_USERNAME:mongodb}:${MONGO_PASSWORD:123456}@${MONGO_HOST:localhost}:${MONGO_PORT:27017}/${PROMOTION_SERVICE_DB:PromotionService}?authSource=admin

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: https://${AUTH0_DOMAIN}

cart:
  service:
    url: ${CART_SERVICE_URL}

product:
  service:
    url: ${PRODUCT_SERVICE_URL}
    
shop:
  service:
    url: ${SHOP_SERVICE_URL}
